# Generated by Django 4.1.5 on 2023-01-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_executor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='label',
            new_name='labels',
        ),
    ]
