# Generated by Django 4.1.5 on 2023-01-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_labels_options_alter_labels_created_at_and_more'),
        ('tasks', '0006_rename_label_tasks_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='label', through='tasks.TaskRelationLabel', to='labels.labels', verbose_name='Label'),
        ),
    ]
