# Generated by Django 4.1.5 on 2023-01-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuses',
            options={'verbose_name': '=Status=', 'verbose_name_plural': '=Statuses='},
        ),
        migrations.AlterField(
            model_name='statuses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='statuses',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Status name'),
        ),
    ]
